export const START_FETCHING_LISTS_CATEGORIES =
  'redux/categories/START_FETCHING_LISTS_CATEGORIES';
export const SUCCESS_FETCHING_LISTS_CATEGORIES =
  'redux/categories/SUCCESS_FETCHING_LISTS_CATEGORIES';
export const ERROR_FETCHING_LISTS_CATEGORIES =
  'redux/categories/ERROR_FETCHING_LISTS_CATEGORIES';

export const START_FETCHING_LISTS_SPEAKERS =
  'redux/categories/START_FETCHING_LISTS_SPEAKERS';
export const SUCCESS_FETCHING_LISTS_SPEAKERS =
  'redux/categories/SUCCESS_FETCHING_LISTS_SPEAKERS';
export const ERROR_FETCHING_LISTS_SPEAKERS =
  'redux/categories/ERROR_FETCHING_LISTS_SPEAKERS';
